# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rlabbiz <rlabbiz@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/06 11:57:51 by rlabbiz           #+#    #+#              #
#    Updated: 2023/09/06 11:57:53 by rlabbiz          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

G++			= g++ -std=c++98
NAME 		= megaphone
FILE_NAME	= megaphone.cpp

all : $(NAME)

$(NAME): $(FILE_NAME)
	$(G++) $(FILE_NAME) -o $(NAME)

fclean: 
	rm -rf $(NAME)

